-- Creation of tables

CREATE DATABASE proj; 
drop database proj; 
USE proj;  

show tables;
CREATE TABLE Brand
(
BrandID INT PRIMARY KEY NOT NULL,
BrandName VARCHAR(100) NOT NULL
);

CREATE TABLE Types
(
TypeID INT PRIMARY KEY NOT NULL,
TypeName VARCHAR(100) NOT NULL
);

CREATE TABLE Tax
(
TaxID INT PRIMARY KEY NOT NULL,
TaxPercentage VARCHAR(100) NOT NULL
);

CREATE TABLE Department
(
DepartmentID INT PRIMARY KEY NOT NULL,
DepartmentName VARCHAR(100) NOT NULL
);

CREATE TABLE LicenceTypes
(
LicID INT PRIMARY KEY NOT NULL,
LicDescription VARCHAR(100) NOT NULL
);
CREATE TABLE Truck
(
TruckID INT PRIMARY KEY NOT NULL,
BrandID INT NOT NULL,
TypeID INT NOT NULL,
TruckDescripion VARCHAR(100) NOT NULL,
FOREIGN KEY (BrandID) REFERENCES Brand(BrandID)
);

CREATE TABLE Employees
(
EmpID INT PRIMARY KEY NOT NULL,
DepID INT NOT NULL,
LicID INT NOT NULL,
EmpFirstName VARCHAR(100) NOT NULL,
EmpLastName VARCHAR(100) NOT NULL,
EmpPhone VARCHAR(100) NOT NULL,
FOREIGN KEY (DepID) REFERENCES department(DepartmentID),
FOREIGN KEY (LicID) REFERENCES licencetypes(LicID)
);

CREATE TABLE Customers
(
CusID INT PRIMARY KEY NOT NULL,
CusName VARCHAR(100) NOT NULL,
CusPhone VARCHAR(100) NOT NULL,
CusAddress VARCHAR(1000) NOT NULL
);
CREATE TABLE CustomerCompany
(
CompanyID INT PRIMARY KEY NOT NULL,
CustomerID INT  NOT NULL,
FOREIGN KEY (CustomerID) REFERENCES Customers (CusID)
);
CREATE TABLE CustomerPerson
(
PersonID INT PRIMARY KEY NOT NULL,
CustomerID INT  NOT NULL,
FOREIGN KEY (CustomerID) REFERENCES Customers (CusID)
);

CREATE TABLE Reservation
(
RevID INT PRIMARY KEY NOT NULL,
CustomerID INT NOT NULL,    
TypeID INT NOT NULL,    
ResDate DATETIME NOT NULL,
Duration INT NOT NULL,
StartDate DATETIME NOT NULL,
EndDate DATETIME NOT NULL,    
FOREIGN KEY (CustomerID) REFERENCES Customers(CusID),
FOREIGN KEY (TypeID) REFERENCES types(TypeID)    
);

CREATE TABLE Mission
(
MissionID INT PRIMARY KEY NOT NULL,
ResID INT NOT NULL,    
EmpID INT NOT NULL,        
TruckID INT NOT NULL,    
ResDate DATETIME NOT NULL,
Millage INT NOT NULL,
StartDate DATETIME NOT NULL,
EndDate DATETIME NOT NULL,    
TerminalName VARCHAR(100),
MeterStartNo DOUBLE NOT NULL,
MeterEndNo DOUBLE NOT NULL,
FOREIGN KEY (EmpID) REFERENCES employees(EmpID),
FOREIGN KEY (TruckID) REFERENCES truck(truckID)    
);

CREATE TABLE Invoice
(
InvID INT PRIMARY KEY NOT NULL,
InvDate DATETIME NOT NULL,
CustomerID INT NOT NULL,   
FOREIGN KEY (CustomerID) REFERENCES customers(CusID)  
);

CREATE TABLE InvoiceLine
(
InvLineID INT PRIMARY KEY NOT NULL,
InvID INT NOT NULL,   
MessionID INT NOT NULL,   
Duration INT NOT NULL,   
DurationCost DOUBLE NOT NULL,
Millage DOUBLE NOT NULL,
MillageCost DOUBLE NOT NULL,
TaxID INT NOT NULL,     
FOREIGN KEY (InvID) REFERENCES invoice(InvID) , 
FOREIGN KEY (MessionID) REFERENCES mission(missionID),
FOREIGN KEY (TaxID) REFERENCES tax(taxID)    
);

CREATE TABLE Payments
(
PaymentID INT PRIMARY KEY NOT NULL,
PayDate DATETIME NOT NULL,   
CustomerID INT NOT NULL,   
InvoiceID INT NOT NULL, 
Amount DOUBLE NOT NULL,    
FOREIGN KEY (InvoiceID) REFERENCES invoice(InvID) , 
FOREIGN KEY (CustomerID) REFERENCES mission(missionID)
);
CREATE TABLE CashPayment
(
PayID INT PRIMARY KEY NOT NULL,
PaymentID INT NOT NULL
);

CREATE TABLE ChequePayment
(
PayID INT PRIMARY KEY NOT NULL,
PaymentID INT NOT NULL,
ChqNo INT NOT NULL,
Bank VARCHAR(100) NOT NULL,
FOREIGN KEY (PaymentID) REFERENCES Payments (PaymentID)

);
CREATE TABLE CreditPayment
(
PayID INT PRIMARY KEY NOT NULL,
PaymentID INT NOT NULL,
CardNo INT NOT NULL,
FOREIGN KEY (PaymentID) REFERENCES Payments (PaymentID)
);
